### ISSUE TITLE
Please upgrade

### ISSUE THREAD

**Issue by yajo** [flathub/io.github.chris2511.xca#1]
Hello, a new release was released lately: https://github.com/chris2511/xca/releases/tag/RELEASE.2.4.0

Would you mind to update this repo?

**Comment by SharkyRawr** [comment]
Hey, thanks for letting me know, I'll get on it sometime this week. Cheers

**Comment by SharkyRawr** [comment]
Pushed the update and it should get published soon! https://github.com/flathub/io.github.chris2511.xca/commit/4f0f530d80e47fd6f0b267317a7cfb4d7b371a16
