### ISSUE TITLE
2.5.0 was released

### ISSUE THREAD

**Issue by q7nm** [flathub/io.github.chris2511.xca#5]
https://github.com/chris2511/xca/releases/tag/RELEASE.2.5.0

**Comment by SharkyRawr** [comment]
Thanks for the heads-up, I will update the flatpak asap.

**Comment by q7nm** [comment]
BTW, `org.kde.Platform` `5-15.21-08` is end-of-life, 
![image](https://github.com/flathub/io.github.chris2511.xca/assets/73637218/1e8f8dd8-c70b-498d-b074-97f92888e137)
it's possible to use even `6.5`.
